### PR TITLE
Corrected prior PR for Platform9

### PR DESCRIPTION
**Pull request by johnjamie**
Included prior PR with Fixed URL

### CODE REVIEW

**Comment by salaboy** [comment]
@johnjamie can you please clarify what does the account provides? If you need to have an account on Google, AWS or Azure, that is not free right?

**Comment by salaboy** [comment]
@johnjamie can you please provide more information? We usually check what is offered to make sure that people find it useful

**Comment by salaboy** [comment]
@johnjamie I cannot merge this PR unless we have a clear understanding of what is being offered by the free account.

**Comment by johnjamie** [comment]
Thanks @salaboy.  The account provides free-forever managed Kubernetes including initial deployment and ongoing management (e.g., cluster operations, upgrades, built-in monitoring with Prometheus and Grafana).  The user provides the infrastructure, and we are very flexible on what that can be - it can be on AWS, Azure, virtual machine, physical server or laptop.  On GCP there are a few more steps than AWS/Azure today but a user can deploy there following our docs at https://docs.platform9.com/kubernetes/tutorials-deploy-kubernetes-on-google-cloud).  If a user does not have any existing infrastructure, they can get a $100 credit on Equinix Metal with code PMKFT (this provides approx. 200 hours of usage at an estimated $0.50/hour; detail on this offer including deployment steps at https://github.com/equinix/terraform-metal-platform9-k8s).  Hope that covers the question.

**Comment by salaboy** [comment]
@johnjamie this is a free "K8s + infrastructure list", maybe we can include the link to Equinix Metal and the code, instead of Platform9 that seems to run on top of existing infrastructure. While I understand that platorm9 can provide a valuable free service, it doesn't compare with other items in the list, where the infrastructure is free and you can create a Kubernetes cluster as part of the trials. What do you think? can we refactor the PR to follow more closely the other items in the list?

**Comment by cruizen** [comment]
While PF9 doesn't fall into the same bucket of 'k8s free infra providers', since we see it as a valuable free service, perhaps it can fall into a class of such services/ tools and still find a mention on the page? 

Disclaimer: PF9 engineer here.

**Comment by salaboy** [comment]
@cruizen thanks for reaching out, and yes.. I believe that there is value in adding these platforms even if they do not fully align with the rest of the list. 
I will copy the content of this PR and I will create a new section for "Other Free tools and services for Kubernetes". Does that work for you? @johnjamie ?

**Comment by johnjamie** [comment]
Thanks @salaboy, and hi @cruizen.  A few thoughts:
1) List scope: I had taken "Free Trials of Managed Kubernetes Services" on the About section to be broader than "free K8s + infrastructure list" so clarification could be helpful.   A suggestion is "Free Managed Kubernetes Services" which would provide the most flexibility to cover different service types, deployment type (public, on-prem etc) and the 3 main types of free offerings (free trial, credits, freemium).
2) Wide variation of types: Looking at the different models on the list I noted that there are some different types of offerings, e.g., Katacoda as a learning platform is quite different from the rest.  I also notice that Codefresh and Platform9 are similar (freemium services, ability to deploy on public or private cloud, credits for a using a specified public cloud).  

Based on 1&2 and reviewing all the listings I would propose that they be refactored as below to cover the landscape of free managed K8s.  Let me know if this make sense:

Proposed groupings:
**Learning Sandboxes - free to use**
Katacoda
Kubernetes.io (new to list; Katacoda based; at https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/)
Play with K8s (new to list; at https://labs.play-with-k8s.com)

**Public Cloud Offerings - typically provides credits / trial period**  
Google Cloud Platform (GKE)
Microsoft Azure (AKS)
IBM Cloud (freemium)
Digital Ocean
Linode (LKE)
Alibaba Cloud
Huawei Cloud

**Freemium Offerings - Deploy on Public Cloud or On-Premises; credit for public cloud infrastructure (or bring your own)**
Platform9 [credit for Packet; also the Azure credit & most other general public cloud news account credits can be used alongside Platform9]
CodeFresh [credit for GKE]

**Integrated Offerings - Kubernetes and underlying infrastructure; free trial / credits**
Redhat OpenShift
Okteto Cloud
Civo Cloud

**Comment by salaboy** [comment]
@johnjamie yeah.. that sounds like a good idea for a refactoring.. sorry that it took me quite a while to get back to this.

**Comment by salaboy** [comment]
I will close this PR due long time inactivity

**Pull request closed without merging**
