### PR TITLE
Adding kubernautic

### PR DESCRIPTION
**Pull request by milindchawre**

### CODE REVIEW

**Comment by salaboy** [comment]
@milindchawre thanks for this contribution, can you please include what is included in the free trial?

**Comment by milindchawre** [comment]
@salaboy done, updated the PR.

**Comment by salaboy** [comment]
@milindchawre awesome thanks!

**Comment by imba-tjd** [comment]
Hi. Did you try to sign it up? I don't understand how to register. I have filled in the Name and Email and clicked SIGN UP, but I didn't get any email, nor is there a place to set password.

image

**Comment by salaboy** [comment]
maybe @milindchawre can help us here.. it was working some time ago

**Pull request merged**
